title: "Eric Tola"
description: "Email: eric.j.tola@gmail.com"

show_downloads: false
google_analytics: false
theme: jekyll-theme-minimal
repository: "https://github.com/etola710/etola710.github.io.git"
